


<head>
<link rel="stylesheet" type="text/css" href="../css/tb_report.css">
</head>


```{r setup, echo= FALSE, warning= FALSE}

# Strings ain't factors
options(stringsAsFactors = FALSE)

# Load the required libraries
library(knitr)
library(xtable)
library(RODBC)


# Set default chunk options
opts_chunk$set(echo = FALSE,
               results = 'asis',
               message = FALSE,
               warning = FALSE,
               error = TRUE)


# Set up default print arguments for printing tables:
# xtable() makes data.frames more suitable for display
# format() converts all of the data.frame comments to character*;
# print() writes the xtable object to HTML

# *print() for xtable throws a tantrum over Date and POSIXct variables,
# so they have to be converted to character before printing 

dfprint <- function(df, printdigits = 2) {
    print(
        xtable(format(df, 
                      na.encode = FALSE, 
                      digits = printdigits, 
                      nsmall = printdigits), 
               align = c("l", "l", rep("c", ncol(df) - 1))
        ),
        type = "html",
        include.rownames = FALSE,
        NA.string = "-")
}



# Set up the database connection
if(interactive()) { 
    plus <- odbcConnect("tbdbplus64") 
} else {
    plus <- odbcConnect("tbdbplus32")
}
    



```



# TB Clinic Data Quality Report
Updated at `r paste(Sys.time())`




## Incomplete LTBI Pickups in the Past Fourteen Days
```{r missed_pickups}

# Query the missed LTBI pickups from the last fourteen days
missed_pu <- sqlQuery(plus, paste("
                                  
    SELECT t.person_id, p.last_name, p.first_name, t.treatment_date
    FROM Drug_Treatment t LEFT OUTER JOIN Person p
    ON t.person_id = p.idnumber
    WHERE dispense_type = 'Pickup'
        AND completed = ''
        AND treatment_date BETWEEN (Now() - 14) AND (Now() - 1)
    ORDER BY treatment_date",
                                  
    sep = "")
                      
)
                                  

dfprint(missed_pu)


```



## Suspects Open for More Than 90 Days
```{r overdue_suspects}

# Query the Case Info records of suspects associated with our clinic
# Ignore any with a status set before 2007
suspects <- sqlQuery(plus, "

    SELECT person_id,
           case_status,
           current_status, 
           current_status_date,
             DATE() - current_status_date AS days_since_status,
		       case_manager
    FROM Case_Info_View
    WHERE current_status = '(Class 5 ) TB Suspect'
        AND case_manager Is Not Null 
        AND agency IN ('Denver Public Health - Metro TB Clinic', 'Select One')
    ORDER BY case_manager, current_status_date
                      
")

# Convert that dt to a date
suspects$current_status_date <- as.Date(suspects$current_status_date)


# Identify suspects to close
suspects$to_close <- FALSE

# Suspects prior to 2007 can stay suspects, but should be closed
suspects$to_close[suspects$current_status_date < as.Date("2007-01-01") &
                  suspects$case_status %in% "Open"] <- TRUE

# Suspects with no status date should also be closed, if possible
suspects$to_close[is.na(suspects$current_status_date) &
                  suspects$case_status %in% "Open"] <- TRUE

# Finally, for cases after 2007, anyone suspected over 90 days should be reclassified
suspects$to_close[suspects$current_status_date >= as.Date("2007-01-01") &
                  suspects$days_since_status > 90] <- TRUE



# Subset to suspects to close, and drop the to_close column
suspects_to_close <- suspects[suspects$to_close, !names(suspects) %in% "to_close"]


dfprint(suspects_to_close)

```





## TSTs with Missing Results
```{r tsts_missing_results}

# Query TSTs either placed or read by our staff but without results
# Disregard tests placed before 2009
tsts_no_result <- sqlQuery(plus, "
                 
    SELECT person_id, date_given, date_read, tst_read_by, result
    FROM TST_View
    WHERE reader_affiliation = 'Denver Metro TB Clinic'
        AND result = 'Select One'
        AND date_given >= #2009-01-01#
    ORDER BY tst_read_by, date_given
                 
")

dfprint(tsts_no_result)


```


## QFTs with Missing Results
```{r qfts_missing_results}

# Query the DPH QFTs
qfts_no_result <- sqlQuery(plus, "
                 
    SELECT person_id, lab, collection_date, result
    FROM QFT_View
    WHERE lab = 'Denver Public Health'
        AND result = 'Select One'
                 
")

# Convert the collection date
qfts_no_result$date_collected <- as.Date(qfts_no_result$collection_date, 
                                         format = "%m/%d/%Y")


dfprint(qfts_no_result[order(qfts_no_result$date_collected), 
                       !names(qfts_no_result) %in% "collection_date"]
)


```


## CXRs Requiring Action
```{r action_cxrs}

# Query the CXRs with action required from TBdb
action_cxrs <- sqlQuery(plus, "
    
    SELECT x.cxr_id, x.person_id, x.cxr_date_taken, x.cxr_date_read,
           x.cxr_read_by, x.cxr_action_text, x.action_required
    FROM CXR_View x LEFT OUTER JOIN TB_Case c
    ON x.person_id = c.person_id
    WHERE c.agency_id = 30
        AND (x.action_required = 'Yes' OR x.action_required Is Null)
    ORDER BY x.cxr_action_text, x.cxr_date_taken
                         
")

# Convert cxr_date_taken to Date
action_cxrs$cxr_date_taken <- as.Date(action_cxrs$cxr_date_taken)

# There are a lot of CXRs with action_required = NA; we only need to address
# those in the last year
action_cxrs_recent <- subset(action_cxrs,
                             action_required %in% "Yes" |
                             (is.na(action_cxrs$action_required) & 
                              action_cxrs$cxr_date_taken >= (Sys.Date() - 365)))

dfprint(action_cxrs_recent)


```






## Encounters with No Staff Responsible






## Visits with No Location
```{r no_location}

# Query encounters with visit_location = 0 ("Select One").
# Only pull face-to-face encounters - that's eval_category = 'Clinical'
# Ignore the NAs - those are imported records that predate TBdb.
enc <- sqlQuery(plus, "
                
    SELECT person_id, eval_date, staff_responsible
    FROM Eval_View
    WHERE visit_location = 'Select One'
        AND eval_category = 'Clinical'
        AND eval_date >= #2011-01-01#
        AND staff_affiliation = 'Denver Metro TB Clinic'
    ORDER BY staff_responsible, eval_date
                
")

dfprint(enc)


```



## Addresses with No County














```{r cleanup}

# Close the database connection
odbcClose(plus)


```



